version: "3.9"

networks:
  php-prova:
    driver: bridge

services:
  php-prova:
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php-prova
    restart: always
    volumes:
      - ./src:/var/www/html
    networks:
      - php-prova
    ports:
      - 8080:80
  mysql-prova:
    platform: linux/x86_64
    image: mysql:8.0.27
    container_name: mysql-prova
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prova
      MYSQL_USER: prova
      MYSQL_PASSWORD: prova
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - php-prova
    ports:
      - 3306:3306